config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :projects

  get 'welcome/index'

  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :name,  :presence => true
  validates :title, :presence => true,
                    :length => { :minimum => 5 }

  belongs_to :author, class_name: "User"
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :technologies_used, presence: true
  validates :name, length: { in: 4..255 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, foreign_key: "author_id"

  def publish!
    published = true
    save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/posts_controller.rb
# Controller for Posts
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # @create_succ = 'Post was successfully created.'
  # @update_succ = 'Post was successfully updated.'
  # @destroy_succ = 'Post was successfully destroyed.'

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        current_user.posts << @post
        @post.author_id = current_user.id
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
  #params.require(:post).permit(:name, :title, :content)
    params.require(:post).permit(:name, :title, :content, (:published if PostPolicy.new(current_user, @post).publish?))
  end
end

app/controllers/projects_controller.rb
# Controller for Projects
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = 'Project has been created.'
      redirect_to @project
    else
      flash.now[:error] = 'Project could not be saved.'
      render :new
    end
  end

  def show
    set_project
  end

  def edit
    set_project
  end

  def update
    set_project

    if @project.update_attributes(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    set_project
    @destroy_string = 'Project was successfully destroyed.'
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: @destroy_string }
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :technologies_used)
  end

  def set_project
    @project = Project.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

# translate the rails flash levels to appropriate Zurb Foundation css classes    def flash_class(level)
  def flash_class(level)
    case level
      when :notice then "info"
      when :success then "success"
      when :error then "error"
      when :alert then "warning"
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<li class="name"><%= link_to 'Articles', posts_path %></li>
<li class="name"><%= link_to 'Projects', projects_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Portfolio" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Portfolio" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body id='application_body'>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div id = 'user_nav'>
      <% if current_user.present? %>
        Signed in as <%= current_user.email %> Not you?
        <%= link_to "Sign Out", destroy_user_session_path, :method => :delete  %>

      <% else %>
        <%= link_to 'Sign Up', new_user_registration_path %> or
        <%= link_to 'Sign In', new_user_session_path %>
      <% end %>
    </div>
    <main id='application_boarder' role="main">

      <%= render 'layouts/messages' %>
       <% flash.each do |key, value| %>
         <div class="alert-box round <%= flash_class(key) %>">
           <%= value %>
         </div>
       <% end %>
       <%= yield %>
    </main>
    <div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

  <% if current_user.role == "editor" %>
    <div class="row collapse">
      <div class="small-3 columns">
        <%= f.label :published, class: "right inline", title: "Is this post published?", data: {tooltip: true } %><br>
      </div>

      <div class="small-9 columns">
        <%= f.check_box :published %>
      </div>
    </div>
  <% end %>

<% end %>

app/views/posts/edit.html.erb
<head>
  <title>Edit Post</title>
</head>

<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<head>
  <title>Posts</title>
</head>

<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @posts.each do |post| %>
      <%if policy(post).index?%>
        <tr id="<%= dom_id(post) %>">
          <td><%= post.name %></td>
          <td><%= post.title %></td>
          <td><%= post.content %></td>
          <td><%= link_to 'Show', post %></td>

        <% if policy(post).update? %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <% end %>

        <% if policy(post).destroy? %>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

        </tr>
      <%end%>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<head>
  <title>New Post</title>
</head>

<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p id="author">
  <b>By:</b>
  <%= @post.author.email %>
</p>

<p id="status">
  <b>Status:</b>
  <%= @post.published? ? "Published" : "Unpublished" %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :technologies_used %><br />
    <%= f.text_area :technologies_used %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', projects_path %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render "form" %>

<%= link_to "Cancel", :back %>

app/views/projects/index.html.erb
<h2>My Portfolio</h2>

<% @projects.each do |project| %>
  <div class='project' id='<%= dom_id(project) %>'>
    <h3><%= project.name %></h3>
    <p><%= project.technologies_used %></p>
    <div class='nav'>
      <%= link_to 'Show', project %>
      <%= link_to 'Edit', edit_project_path(project) %>
      <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?'} %>
    </div>
  </div>
<% end %>

<br />
<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form" %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<p>Technologies used: <%=@project.technologies_used %></p>

app/views/welcome/index.html.erb
<html>
<head>
  <title>Welcome</title>
</head>
<body>
<h1>Welcome to my site!</h1>
<%= link_to "My Blog", posts_path %>
<p>My name is Nick Manos and I am a web developer at the Code Fellows Rails Dev Accelerator.<p>
</body>
</html>